# Default initial positions for rectangular_gantry's ros2_control fake system

initial_positions:
  gripper_left_joint: 0
  gripper_right_joint: 0
  map_to_xaxis: 0
  xaxis_to_yaxis: 0
  yaxis_to_zaxis: 0
  zaxis_to_eemount: 0