# MoveIt uses this configuration for controller management

moveit_controller_manager: moveit_simple_controller_manager/MoveItSimpleControllerManager

moveit_simple_controller_manager:
  controller_names:
    - prismatic_chain_controller
    - ee_controller

  prismatic_chain_controller:
    type: FollowJointTrajectory
    joints:
      - map_to_xaxis
      - xaxis_to_yaxis
      - yaxis_to_zaxis
      - zaxis_to_eemount
    action_ns: follow_joint_trajectory
  ee_controller:
    type: FollowJointTrajectory
    joints:
      - gripper_left_joint
      - gripper_right_joint
    action_ns: follow_joint_trajectory