controller_list:
- name: arm_group_controller
  action_ns: follow_joint_trajectory
  type: joint_trajectory_controller/JointTrajectoryController
  default: true
  joints:
    - joint_a1
    - joint_a2
    - joint_a3
    - joint_a4
    - joint_a5
    - joint_a6
