# This config file is used by ros2_control
controller_manager:
  ros__parameters:
    update_rate: 100  # Hz

    arm_group_controller:
      type: joint_trajectory_controller/JointTrajectoryController


    joint_state_broadcaster:
      type: joint_state_broadcaster/JointStateBroadcaster
      joints:
        - joint_a1
        - joint_a2
        - joint_a3
        - joint_a4
        - joint_a5
        - joint_a6
      state_interfaces:
        - position
        - velocity
        - effort





arm_group_controller:
  ros__parameters:
    joints:
      - joint_a1
      - joint_a2
      - joint_a3
      - joint_a4
      - joint_a5
      - joint_a6
    command_interfaces:
      - position
    state_interfaces:
      - position
      - velocity
    gains:
      joint_a1: {p: 100.0, i: 0.01, d: 10.0, i_clamp: 0.1, ff_velocity_scale: 1.0}
      joint_a2: {p: 100.0, i: 0.01, d: 10.0, i_clamp: 0.1, ff_velocity_scale: 1.0}
      joint_a3: {p: 100.0, i: 0.01, d: 10.0, i_clamp: 0.1, ff_velocity_scale: 1.0}
      joint_a4: {p: 100.0, i: 0.01, d: 10.0, i_clamp: 0.1, ff_velocity_scale: 1.0}
      joint_a5: {p: 100.0, i: 0.01, d: 10.0, i_clamp: 0.1, ff_velocity_scale: 1.0}
      joint_a6: {p: 100.0, i: 0.01, d: 10.0, i_clamp: 0.1, ff_velocity_scale: 1.0}
    open_loop_control: false

